[project]
name = "python-infrakit-dev"
version = "0.1.0"
description = "A comprehensive Python developer infrastructure toolkit"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "google-genai>=1.69.0",
    "isort>=8.0.1",
    "openai>=2.30.0",
    "pydantic>=2.12.5",
    "python-dotenv>=1.2.2",
    "pyyaml>=6.0.3",
    "tqdm>=4.67.3",
    "typer>=0.24.1",
]

[dependency-groups]
dev = [
    "mypy>=1.19.1",
    "pytest>=9.0.2",
    "pytest-cov>=7.1.0",
    "ruff>=0.15.7",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
infrakit = "infrakit.cli.main:main"
ik       = "infrakit.cli.main:main"

[project.urls]
Homepage = "https://github.com/chiragg21/infrakit"
Repository = "https://github.com/chiragg21/infrakit"

[tool.hatch.build.targets.wheel]
packages = ["infrakit"]
